In [1]:
import numpy as np
addr = np.empty([0,4], dtype=np.int32)
print(addr.shape)

(0, 4)


In [2]:
addr0 = np.empty([4], dtype=np.int32)
print(addr0.shape)
addr1 = np.expand_dims(addr0, axis=0)
print(addr1.shape)

(4,)
(1, 4)


In [6]:
aa=np.ones((5, 1), dtype=np.int32)
print(aa)
print(2*aa)
print(aa*2)

[[1]
 [1]
 [1]
 [1]
 [1]]
[[2]
 [2]
 [2]
 [2]
 [2]]
[[2]
 [2]
 [2]
 [2]
 [2]]


In [1]:
import numpy as np
from io import StringIO
c=StringIO(' 1 2\n 3 4')
a=np.loadtxt(c)
print(a)

[[1. 2.]
 [3. 4.]]


In [3]:
import numpy as np
import os

file_list = ['multi_else_ilxl.pts','multi_grizzly_ilxl.pts',
             'multi_high_amp_continuous_ilxl.pts',
             'multi_high_amplitude_ilxl.pts','multi_low_amp_dips_ilxl.pts',
             'multi_low_amplitude_ilxl.pts','multi_low_coherency_ilxl.pts',
             'multi_salt_ilxl.pts','multi_steep_dips_ilxl.pts']

# dir for classification data
classification_data_dir = 'F3_classification_data'
# actual classification data file names
files_with_dir=[]
for file in file_list:
    files_with_dir.append(os.path.join(classification_data_dir, file))
file_list = files_with_dir

#
aa = np.loadtxt(file_list[0], skiprows=0, usecols = range(3), dtype = np.float32)
print(aa.shape)

(20070, 3)


In [17]:
print(aa[0])
print(len(aa))
cc = np.ones((len(aa),1),dtype = np.int32)
print(cc.shape)

[339. 330. 716.]
20070
(20070, 1)


In [18]:
print(aa[0])
print(aa[1])

#
i = 2

#
bb = np.append(aa,i*cc,axis=1)
print(bb.shape)
print(bb[0])
print(bb[1])

[339. 330. 716.]
[339. 330. 712.]
(20070, 4)
[339. 330. 716.   2.]
[339. 330. 712.   2.]


In [19]:
#
adr_list = np.empty([0,4], dtype = np.int32)
#
adr_list = np.append(adr_list, bb ,axis=0)
print(adr_list.shape)
print(adr_list[0])
print(adr_list[1])

(20070, 4)
[339. 330. 716.   2.]
[339. 330. 712.   2.]


In [20]:
#
ex_adjust = True

# Make an array of that holds the number of each example provided, if equalization is needed
if ex_adjust:
    len_array = np.zeros(len(file_list),dtype = np.float32)
    for i in range(len(file_list)):
        len_array[i] = len(np.loadtxt(file_list[i], skiprows=0, usecols = range(3), dtype = np.float32))

    # Cnvert this array to a multiplier that determines how many times a given class set needs to be
    len_array /= max(len_array)
    multiplier = 1//len_array
#
print(multiplier.shape)
print(multiplier)

(9,)
[1. 1. 1. 1. 1. 1. 1. 2. 2.]


In [ ]:
# preallocate space for the adr_list, the output containing all the adresses and classes
adr_list = np.empty([0,4], dtype = np.int32)

# Itterate through the list of example adresses and store the class as an integer
for i in range(len(file_list)):
    a = np.loadtxt(file_list[i], skiprows=0, usecols = range(3), dtype = np.int32)
    adr_list = np.append(adr_list,np.append(a,i*np.ones((len(a),1),dtype = np.int32),axis=1),axis=0)

    # If desired copy the entire list by the multiplier calculated
    if ex_adjust:
        for k in range(int(multiplier[i])-1):
            adr_list = np.append(adr_list,np.append(a,i*np.ones((len(a),1),dtype = np.int32),axis=1),axis=0)

In [21]:
y = np.zeros((2, 3, 4))
print(y.shape)
print(y.shape[1])

(2, 3, 4)
3
